
package modules;

import core.auth.Authentication;
import core.auth.AuthenticationListener;

import core.system.ApplicationInfo;
import core.system.LoginDialog;
import core.system.PrivilegeDialog;
import core.user.UserManajemen;
import java.awt.Frame;
import javax.swing.JOptionPane;


/**
 *
 * @author PRAM WEE
 */
public class MainFrame extends javax.swing.JFrame implements AuthenticationListener {

    private static MainFrame instance;

    private MainFrame() {
        setExtendedState(Frame.MAXIMIZED_BOTH);
        initComponents();
        setTitle(ApplicationInfo.TITLE + " Versi " + ApplicationInfo.VERSION + " oleh " + ApplicationInfo.AUTHOR);
        scrollUtama.setViewportView(MenuUtama.getInstance());

    }

    public static MainFrame getInstance() {
        if (instance == null) {
            instance = new MainFrame();
            core.auth.Authentication.getInstance().registerListener(MainFrame.getInstance());
        }
        return instance;
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar6 = new javax.swing.JToolBar();
        jButton8 = new javax.swing.JButton();
        scrollUtama = new javax.swing.JScrollPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuSistem = new javax.swing.JMenu();
        mnuManajemenPemakai = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuHome = new javax.swing.JMenuItem();
        mnuPasien = new javax.swing.JMenuItem();
        mnuGejala = new javax.swing.JMenuItem();
        mnuPenyakit = new javax.swing.JMenuItem();
        mnuRekamMedis = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Kepegawaian Purworejo Versi 1.0");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("frameMain"); // NOI18N
        setState(Frame.MAXIMIZED_BOTH);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jToolBar6.setRollover(true);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/core/images/KoneksiKlaster.jpg"))); // NOI18N
        jButton8.setText("Pairwise Klaster");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(jButton8);

        scrollUtama.setBorder(null);

        mnuSistem.setMnemonic('f');
        mnuSistem.setText("File");

        mnuManajemenPemakai.setText("Manajemen Pemakai");
        mnuManajemenPemakai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManajemenPemakaiActionPerformed(evt);
            }
        });
        mnuSistem.add(mnuManajemenPemakai);

        jMenuItem6.setText("Logout");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuSistem.add(jMenuItem6);

        jMenuItemExit.setMnemonic('x');
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        mnuSistem.add(jMenuItemExit);

        jMenuBar2.add(mnuSistem);

        jMenu4.setText("Modul");

        mnuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home.gif"))); // NOI18N
        mnuHome.setText("Home");
        mnuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHomeActionPerformed(evt);
            }
        });
        jMenu4.add(mnuHome);

        mnuPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pelanggan.gif"))); // NOI18N
        mnuPasien.setText("Pasien");
        mnuPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPasienActionPerformed(evt);
            }
        });
        jMenu4.add(mnuPasien);

        mnuGejala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/obat.gif"))); // NOI18N
        mnuGejala.setText("Gejala");
        mnuGejala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGejalaActionPerformed(evt);
            }
        });
        jMenu4.add(mnuGejala);

        mnuPenyakit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log.gif"))); // NOI18N
        mnuPenyakit.setText("Penyakit");
        mnuPenyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPenyakitActionPerformed(evt);
            }
        });
        jMenu4.add(mnuPenyakit);

        mnuRekamMedis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/glycerol_a.gif"))); // NOI18N
        mnuRekamMedis.setText("Rekam Medis");
        mnuRekamMedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRekamMedisActionPerformed(evt);
            }
        });
        jMenu4.add(mnuRekamMedis);

        jMenuBar2.add(jMenu4);

        jMenu2.setMnemonic('h');
        jMenu2.setText("Help");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/core/images/KoneksiNode.jpg"))); // NOI18N
        jMenuItem2.setMnemonic('a');
        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-723)/2, (screenSize.height-567)/2, 723, 567);
    }// </editor-fold>//GEN-END:initComponents
    private void formWindowStateChanged (java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
// TODO add your handling code here:

    }//GEN-LAST:event_formWindowStateChanged

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void mnuPenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPenyakitActionPerformed
        MenuUtama.getInstance().setModul(3);
}//GEN-LAST:event_mnuPenyakitActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AboutBox.getInstance().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuManajemenPemakaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManajemenPemakaiActionPerformed
        if (PrivilegeDialog.getInstance().isCorrect()) {
            UserManajemen.getInstance().setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Root password tidak sesuai");
        }
}//GEN-LAST:event_mnuManajemenPemakaiActionPerformed

    private void mnuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHomeActionPerformed
        MenuUtama.getInstance().setModul(0);
}//GEN-LAST:event_mnuHomeActionPerformed

    private void mnuPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPasienActionPerformed
        MenuUtama.getInstance().setModul(1);
}//GEN-LAST:event_mnuPasienActionPerformed

    private void mnuGejalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGejalaActionPerformed
        MenuUtama.getInstance().setModul(2);
}//GEN-LAST:event_mnuGejalaActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.setVisible(false);
        LoginDialog.getInstance().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void mnuRekamMedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRekamMedisActionPerformed
        MenuUtama.getInstance().setModul(4);
}//GEN-LAST:event_mnuRekamMedisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JToolBar jToolBar6;
    private javax.swing.JMenuItem mnuGejala;
    private javax.swing.JMenuItem mnuHome;
    private javax.swing.JMenuItem mnuManajemenPemakai;
    private javax.swing.JMenuItem mnuPasien;
    private javax.swing.JMenuItem mnuPenyakit;
    private javax.swing.JMenuItem mnuRekamMedis;
    private javax.swing.JMenu mnuSistem;
    private javax.swing.JScrollPane scrollUtama;
    // End of variables declaration//GEN-END:variables
    public void userLogin() {
        if(Authentication.getInstance().getUserInfo().getRole().equalsIgnoreCase("administrator")){
            mnuManajemenPemakai.setVisible(true);
        }else{
            mnuManajemenPemakai.setVisible(false);
        }
        this.setVisible(true);
    }

    public void userNotLogin() {

    }
}
