
package modules.rekmed;

import core.gui.InputPanel;
import javax.swing.JOptionPane;
import modules.ApplicationStartup;

/**
 *
 * @author  PRAM WEE
 */
public class BeanRekmed extends InputPanel {

    /** Creates new form BeanForm */
    public BeanRekmed() {
        initComponents();
        super.setPnlUtama(pnlUtama);
        ApplicationStartup.getInstance().initialize();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUtama = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNamaPenyakit = new core.dataview.JTextFieldEx();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtDeskripsi1 = new core.dataview.JTextFieldEx();
        jLabel9 = new javax.swing.JLabel();
        txtDeskripsi2 = new core.dataview.JTextFieldEx();
        jLabel10 = new javax.swing.JLabel();
        jCombBoxEx1 = new core.dataview.JCombBoxEx();
        jCombBoxEx2 = new core.dataview.JCombBoxEx();
        jButton1 = new javax.swing.JButton();

        jLabel3.setText("Tanggal Periksa");

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel7.setText("Pasien");

        txtNamaPenyakit.setText("jTextFieldEx1");
        txtNamaPenyakit.setFieldName("nama_penyakit");

        jTable1.setModel(new modules.rekmed.RekmedTableModel());
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        jLabel8.setText("Keterangan");

        txtDeskripsi1.setText("jTextFieldEx1");
        txtDeskripsi1.setFieldName("deskripsi");

        jLabel9.setText("Diagnosa");

        txtDeskripsi2.setText("jTextFieldEx1");
        txtDeskripsi2.setFieldName("deskripsi");

        jLabel10.setText("Suspect Penyakit");

        jButton1.setText("Proses Diagnosa");

        javax.swing.GroupLayout pnlUtamaLayout = new javax.swing.GroupLayout(pnlUtama);
        pnlUtama.setLayout(pnlUtamaLayout);
        pnlUtamaLayout.setHorizontalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(61, 61, 61)
                        .addComponent(jCombBoxEx1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtamaLayout.createSequentialGroup()
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(68, 68, 68)
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCombBoxEx2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addGroup(pnlUtamaLayout.createSequentialGroup()
                                .addComponent(btnOK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal))
                            .addComponent(txtNamaPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeskripsi2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(txtDeskripsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUtamaLayout.setVerticalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtamaLayout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNamaPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jCombBoxEx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtDeskripsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtDeskripsi2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCombBoxEx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBatal)
                            .addComponent(btnOK))))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Gejala Penyakit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        super.performOK();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        super.performCancel();
    }//GEN-LAST:event_btnBatalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton jButton1;
    private core.dataview.JCombBoxEx jCombBoxEx1;
    private core.dataview.JCombBoxEx jCombBoxEx2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlUtama;
    private core.dataview.JTextFieldEx txtDeskripsi1;
    private core.dataview.JTextFieldEx txtDeskripsi2;
    private core.dataview.JTextFieldEx txtNamaPenyakit;
    // End of variables declaration//GEN-END:variables

    @Override
    public void fillControl(String[][] data) {
    }

    @Override
    public boolean validateAllControls() {
        boolean lolos;
        lolos = true;
        double d;

        try {
            d = Integer.parseInt(txtNamaPenyakit.getSQLValue());
            lolos = false;
        } catch (java.lang.NumberFormatException ex) {
            ex.printStackTrace();
            //bener
        }
        
//        try {
//            d = Integer.parseInt(txtDeskripsi.getSQLValue());
//            lolos = false;
//        } catch (java.lang.NumberFormatException ex) {
//            ex.printStackTrace();
//        }

//        if (lolos) {
//            if (txtDeskripsi.getSQLValue().equals("") && txtDeskripsi.getSQLValue().length() <= 2) {
//                return false;
//            }

          
            if (txtNamaPenyakit.getSQLValue().equals("") && txtNamaPenyakit.getSQLValue().length() <= 2) {
                return false;
            }
           
//        }else return false;

        return true;


    }

    @Override
    public void clearField() {
        txtNamaPenyakit.requestFocus();
    }

    @Override
    public void setVisible(boolean aFlag) {
        if (aFlag) {
        }
        super.setVisible(aFlag);
    }

    @Override
    protected String delegateGetInsertSql() {
        return "insert into penyakit(nama_penyakit," +
                "deskripsi)" +
                "values('" +
                txtNamaPenyakit.getText() + "','" +

                ")";
    }

    @Override
    protected String delegateGetUpdateSql(String rowId) {
        return "update penyakit set nama_penyakit='" + txtNamaPenyakit.getText() + "'," +
            
                
                " where idpenyakit=" + rowId;
    }

    @Override
    protected void afterInsert() {
        super.afterInsert();
        
    }

    @Override
    protected void afterUpdate(String rowToBeEdited) {
        super.afterUpdate(rowToBeEdited);
    }
    
}
