package modules.servismobil;

import core.gui.DateChooser;
import core.gui.InputPanel;
import core.system.Startup;
import modules.ApplicationStartup;

/**
 *
 * @author  PRAM WEE
 */
public class BeanServisMobil extends InputPanel {

    /** Creates new form BeanForm */
    public BeanServisMobil() {
        initComponents();
        super.setPnlUtama(pnlUtama);
        ApplicationStartup.getInstance().initialize();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUtama = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        txtKmServis = new core.dataview.JTextFieldEx();
        jLabel9 = new javax.swing.JLabel();
        txtTanggalServis = new core.dataview.JTextFieldEx();
        jLabel10 = new javax.swing.JLabel();
        cboPelanggan = new core.dataview.JCombBoxEx();
        jLabel11 = new javax.swing.JLabel();
        btnTanggalServis = new javax.swing.JButton();

        btnSimpan.setMnemonic('S');
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setMnemonic('B');
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        txtKmServis.setFieldName("km_servis");

        jLabel9.setText("KM Servis");

        txtTanggalServis.setFieldName("tanggal_servis");

        jLabel10.setText("Tanggal Servis");

        cboPelanggan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "xx", "xxxx" }));
        cboPelanggan.setFieldName("idpelanggan");
        cboPelanggan.setSqlSelect("select idpelanggan,nama from pelanggan order by nama");

        jLabel11.setText("Pemilik");

        btnTanggalServis.setMnemonic('S');
        btnTanggalServis.setText("..");
        btnTanggalServis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanggalServisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUtamaLayout = new javax.swing.GroupLayout(pnlUtama);
        pnlUtama.setLayout(pnlUtamaLayout);
        pnlUtamaLayout.setHorizontalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUtamaLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(cboPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addGap(49, 49, 49))
                            .addComponent(jLabel11))
                        .addGap(36, 36, 36))
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(6, 6, 6)
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKmServis, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlUtamaLayout.createSequentialGroup()
                                .addComponent(txtTanggalServis, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTanggalServis))
                            .addGroup(pnlUtamaLayout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal)))
                        .addContainerGap(49, Short.MAX_VALUE))))
        );
        pnlUtamaLayout.setVerticalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cboPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtKmServis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTanggalServis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnTanggalServis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        /*
         * cek dulu, apakah kelas tersebut masih ada.
         */

        super.performOK();
}//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        super.performCancel();
}//GEN-LAST:event_btnBatalActionPerformed

    private void btnTanggalServisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanggalServisActionPerformed
        DateChooser calendar = new DateChooser(Startup.getInstance().getMainFrame());
        calendar.setVisible(true);
        if (calendar.isDone()) {
            txtTanggalServis.setText(calendar.getChoosedDate());
        }
}//GEN-LAST:event_btnTanggalServisActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTanggalServis;
    private core.dataview.JCombBoxEx cboPelanggan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlUtama;
    private core.dataview.JTextFieldEx txtKmServis;
    private core.dataview.JTextFieldEx txtTanggalServis;
    // End of variables declaration//GEN-END:variables
    @Override
    public void fillControl(String[][] data) {
    }

    @Override
    public void clearField() {
        cboPelanggan.requestFocus();
    }

    @Override
    public void setVisible(boolean aFlag) {
        if (aFlag) {
        }
        super.setVisible(aFlag);
    }

    @Override
    protected String delegateGetInsertSql() {
        String sql = "insert into `pelanggan_servis`(km_servis,tanggal_servis,idpelanggan" +
                ") " +
                "values(" +           
                txtKmServis.getText() + ",'" +
                txtTanggalServis.getText() + "'," +
                cboPelanggan.getAutoIdFromSelectedIndex() +
                ")";
        //System.out.println(sql);
        return sql;
    }

    @Override
    protected String delegateGetUpdateSql(String rowId) {
        String sql = "update `pelanggan_servis` set " +                
                "km_servis=" + txtKmServis.getText() + "," +
                "tanggal_servis='" + txtTanggalServis.getText() + "'," +
                "idpelanggan=" + cboPelanggan.getAutoIdFromSelectedIndex() +
                " where idpelanggan_servis=" + rowId;
        //System.out.println(sql);
        return sql;
    }

    @Override
    public boolean validateAllControls() {
        return true;
  

    }
}
