/*
 * Beandaftar_rumah_sakit.java
 *
 * Created on 07 April 2008, 20:58
 */
package modules.servismobil;

import core.gui.JDialogEntry;
import core.system.Startup;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author  QROEL GANTENX
 */
public class InputServisItem extends JDialogEntry {

    private static InputServisItem singleton;

    public static InputServisItem getInstance() {
        if (singleton == null) {
            singleton = new InputServisItem(Startup.getInstance().getMainFrame());
            singleton.setTableController(DaftarServisMobil.getTableController());
            singleton.clearFields();

            singleton.postInit(); // -- baru diperkenalkan di form entry kartu ini, misalnya u/ pengisian combo box
        }
        return singleton;
    }
  

    /** Creates new form BeanForm */
    private InputServisItem(JFrame parent) {
        super(parent, "`pelanggan_servis_item`");
        initComponents();
        setPnlUtama(jPanel1);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSimpan = new javax.swing.JButton();
        btnLanjut = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cboItemServis = new core.dataview.JCombBoxEx();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHarga = new core.dataview.JTextFieldEx();
        txtJumlah = new core.dataview.JTextFieldEx();

        setTitle("Jenis Layanan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btnSimpan.setMnemonic('S');
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnLanjut.setMnemonic('a');
        btnLanjut.setText("Lanjut");
        btnLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutActionPerformed(evt);
            }
        });

        btnBatal.setMnemonic('B');
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel8.setText("Jenis Layanan");

        cboItemServis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EKO", "irul", "RAHMAT", "sinta" }));
        cboItemServis.setFieldName("iditem_servis");
        cboItemServis.setSqlSelect("select iditem_servis, nama_item from item_servis order by nama_item");
        cboItemServis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboItemServisActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga");

        jLabel4.setText("Jumlah");

        txtHarga.setFieldName("harga");

        txtJumlah.setFieldName("jumlah");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(cboItemServis, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                    .addComponent(jLabel4))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cboItemServis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLanjut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLanjut)
                .addGap(6, 6, 6)
                .addComponent(btnBatal)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Input Tiket");

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-417)/2, (screenSize.height-173)/2, 417, 173);
    }// </editor-fold>//GEN-END:initComponents
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        super.performSimpan();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutActionPerformed
        super.perfromLanjut();
    }//GEN-LAST:event_btnLanjutActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        singleton.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void cboItemServisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboItemServisActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_cboItemServisActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//        ApplicationStartup.getInstance().initialize();
//        int idtiket = DaftarServisMobil.getInstance().getServisPelangganId();
//        String data[][] = DB.getInstance().getDataSet("SELECT t.idkapal FROM tiket t, kapal k where k.idkapal = t.idkapal and id=" + idtiket, false);
//        cboKapal.setSelectedIndexToAutoId(data[0][0]);
        cboItemServis.reload();
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnLanjut;
    private javax.swing.JButton btnSimpan;
    private core.dataview.JCombBoxEx cboItemServis;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private core.dataview.JTextFieldEx txtHarga;
    private core.dataview.JTextFieldEx txtJumlah;
    // End of variables declaration//GEN-END:variables
    public void clearField() {
        cboItemServis.requestFocus();
    }

    @Override
    protected String delegateGetInsertSql() {
        int idpelanggan_servis = DaftarServisMobil.getInstance().getServisPelangganId();
        String sql = "insert into `pelanggan_servis_item`" +
                "(idpelanggan_servis," +
                "iditem_servis," +
                "jumlah," +
                "harga" +
              ") " +
                "values(" + idpelanggan_servis + "," +
                cboItemServis.getAutoIdFromSelectedIndex() + "," +
                txtJumlah.getText() + "," +
                txtHarga.getText() + 
                ")";

        return sql;
    }

    @Override
    protected String delegateGetUpdateSql(int rowId) {
        String sql = " update `pelanggan_servis_item` set " +
                " iditem_servis=" + cboItemServis.getAutoIdFromSelectedIndex() + "," +
                " jumlah=" + txtJumlah.getText() + "," +
                " harga=" + txtHarga.getText() + 
                " where idpelanggan_servis_item=" + rowId;
        return sql;
    }

    @Override
    protected void delegateFillControl(ResultSet rs) {
        try {
            cboItemServis.setSelectedIndexToAutoId(rs.getString("iditem_servis"));
            txtJumlah.setText(rs.getString("jumlah"));
            txtHarga.setText(rs.getString("harga"));
        } catch (SQLException ex) {
            Logger.getLogger(InputServisItem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    @Override
    protected void clearFields() {
        cboItemServis.setSelectedIndex(0);
       
        txtHarga.setText("");
        txtJumlah.setText("1");

    }

    @Override
    protected void postInit() {
//        if(super.get)
    }

    @Override
    protected void afterInsert() {
    }

    public void afterInsert(int idtiket, String kelas, int jumlah) {
    }

    @Override
    public void beforeHapus(int rowToBeErased) {
        beforeUpdate(rowToBeErased);
    }

    @Override
    public void beforeUpdate(int rowToBeEdited) {
    }

    @Override
    protected void afterUpdate(int rowToBeEdited) {

    }

    @Override
    public void afterHapus(int rowToBeErased) {

    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        if (b) {

            cboItemServis.reload();
        }
    }
// CEK ada validateAllControls
//    @Override
//    public boolean validateAllControls() {
//        return !txtHarga.mustNumber() && !txtHarga.isEmpty() && !txtHarga.toFew() &&
//                !txtJumlah.mustNumber() && !txtJumlah.isEmpty() && !txtJumlah.toFew() &&
//                txtJumlah.mustNumber() && (txtJumlah.getAsInt() > 0);
//
//    }
}
